arrowParens: always
bracketSpacing: true
jsxSingleQuote: false
jsxBracketSameLine: true
printWidth: 100
quoteProps: as-needed
semi: false
singleQuote: true
tabWidt": 2
trailingComma: none
useTabs: false
